### ISSUE TITLE
Remove pages that aren't crucial

### ISSUE THREAD

**Issue by nickedwards109** [Machine-Tool-Simulator/Simulator-Web-Client#49]
There are a few pages that teach functionality we got from the original lathe instruction video, but it's functionality that isn't commonly used (Power Feed, Return Home, and Set Tool Number). The Do One Taper page is a gray area here, because it teaches functionality that is used occasionally but may be beyond the scope of the current iteration. Let's remove all of those pages in order to focus on the fundamentals and keep the scope tight for now.

Remove the following pages:
  * Power Feed
  * Return Home
  * Set Tool Number
  * Do One Taper

**Comment by sulljohn** [comment]
These are currently resolved on my branch. This will be closed once my branch has been merged to master.

**Comment by nickedwards109** [comment]
Nice, thanks for taking care of this @sulljohn !
